---
- name: Configurar SSH
  hosts: all
  become: yes  # Add this line to use sudo/root privileges
  tasks:
    - name: Bloquear login do root e autenticação por senha
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - { regexp: "^PermitRootLogin", line: "PermitRootLogin no" }
        - { regexp: "^PasswordAuthentication", line: "PasswordAuthentication no" }

    - name: Reiniciar serviço SSH
      service:
        name: sshd
        state: restarted
