Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian12"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "p01_Wiliam"
    vb.memory = 1024
  end
  
  # Configuração de rede bridge
  config.vm.network "public_network", bridge: "enp4s0"
  # Mantenho também a rede privada original
  config.vm.network "private_network", ip: "192.168.57.10"
  
  # Configuração de discos adicionais
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["createhd", "--filename", "disk1.vdi", "--size", 10240]
    vb.customize ["createhd", "--filename", "disk2.vdi", "--size", 10240]
    vb.customize ["createhd", "--filename", "disk3.vdi", "--size", 10240]
    vb.customize ["storageattach", :id, "--storagectl", "SATA Controller", "--port", 1, "--device", 0, "--type", "hdd", "--medium", "disk1.vdi"]
    vb.customize ["storageattach", :id, "--storagectl", "SATA Controller", "--port", 2, "--device", 0, "--type", "hdd", "--medium", "disk2.vdi"]
    vb.customize ["storageattach", :id, "--storagectl", "SATA Controller", "--port", 3, "--device", 0, "--type", "hdd", "--medium", "disk3.vdi"]
  end
  
  # Configuração do Ansible para provisionamento automático
  # Sincronizar pasta local com a VM
  config.vm.synced_folder ".", "/vagrant", create: true
  
  # Provisionar usando Ansible
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.become = true
  end
end
